### ISSUE TITLE
Doesn't work for slack...

### ISSUE THREAD

**Issue by kayibal** [RPing/Ver.bot#2]
![](https://preview.ibb.co/eAArJR/Screen_Shot_2017_11_17_at_13_25_33.png)

**Comment by kayibal** [comment]
Nevermind It works if I private message him

**Comment by RPing** [comment]
Yes, because it only support private message on Slack now.
The reason is that Slack event api will send EVERY message in channel if Ver.bot want to support in channel. That's too annoying IMO 😞
