### ISSUE TITLE
Allow for channel communication

### ISSUE THREAD

**Issue by kerrermanisNL** [RPing/Ver.bot#3]
Would be nice if `Ver.bot` could communicate with a channel instead of only DM's. That way I can, for example, notify my whole project team whenever a new version of React comes out. Than anyone can pick it up, instead of just me :)

**Comment by RPing** [comment]
The reason why `Ver.bot` doesn't support channels on Slack is that event api will send EVERY message in channel to my `Ver.bot` webhook server. It not only annoyed but a little bit invade channel's privacy.

So, please try it out on `Telegram` or `Skype` 😃
